name: xml_widget
description:
  A library that could parse xml file to flutter widgets, supporting color,style and theme,
  and dynamically change by script.
version: 0.2.0
homepage: https://github.com/lindeer/durian

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.5.0
  xml: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1

flutter:
