name: xml_flutter
description: A library transforming weixin mini program to xml_widget.
version: 1.0.0
homepage: https://github.com/lindeer/xml-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
